import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import Image from "next/image";
import Link from "next/link";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Daraiba Rafiq Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          {children}
          <div className='fixed text-green-400 bottom-2 lg:bottom-5 right-4 lg:right-10 z-50'>
            <Link href={"https://wa.link/nd37q1"} target="_blank">
              <Image
                src={"/w.png"}
                alt="WhatsApp"
                width={60}
                height={60}
                className="rounded-full w-[60px] h-[60px] cursor-pointer hover:scale-110 transition-transform duration-300"
              />
            </Link>
          </div>
    
        </ThemeProvider>
      </body>
    </html>
  );
}
